Add support for -c.

diff --git a/src/msys2-init b/src/msys2-init
--- a/src/msys2-init
+++ b/src/msys2-init
@@ -6,7 +6,7 @@ set -e
 . /etc/msys2-env
 
 msys2-install
-msys2-wrapper "echo restart"
+msys2-shell -c "echo restart"
 
 set -x
 # make a symbolic link from unix $HOME to msys2 $HOME
@@ -27,26 +27,26 @@ echo "Server = http://repo.msys2.org/msys/\$arch" > ${MSYS_ROOT}/etc/pacman.d/mi
 echo "Server = http://repo.msys2.org/mingw/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
 echo "Server = http://repo.msys2.org/mingw/x86_64" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw64
 
-msys2-wrapper "pacman -Sy"
-msys2-wrapper "pacman -S --needed --noconfirm msys2-runtime pacman pacman-mirrors"
+msys2-shell -c "pacman -Sy"
+msys2-shell -c "pacman -S --needed --noconfirm msys2-runtime pacman pacman-mirrors"
 
 # Set new msys2 mirror again
 echo "Server = http://repo.msys2.org/msys/\$arch" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys
 echo "Server = http://repo.msys2.org/mingw/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
 echo "Server = http://repo.msys2.org/mingw/x86_64" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw64
 
-msys2-wrapper "pacman -Sy"
-msys2-wrapper "pacman -Su --noconfirm"
-msys2-wrapper "pacman -S --needed --noconfirm msys2-devel base-devel git"
+msys2-shell -c "pacman -Sy"
+msys2-shell -c "pacman -Su --noconfirm"
+msys2-shell -c "pacman -S --needed --noconfirm msys2-devel base-devel git"
 
-# msys2-wrapper "git config --global --add user.name \"MSYS2 Travis Bot\" || echo FIXME git config fail"
-# msys2-wrapper "git config --global --add user.email \"MSYS2@DUMMY.MAIL\""
+# msys2-shell -c "git config --global --add user.name \"MSYS2 Travis Bot\" || echo FIXME git config fail"
+# msys2-shell -c "git config --global --add user.email \"MSYS2@DUMMY.MAIL\""
 git config --global --add user.name "MSYS2 Travis Bot"
 git config --global --add user.email "MSYS2@DUMMY.MAIL"
 
-msys2-wrapper "pacman -S --needed --noconfirm wget"
+msys2-shell -c "pacman -S --needed --noconfirm wget"
 
-msys2-wrapper "pacman -S --needed --noconfirm mingw-w64-i686-xz"
+msys2-shell -c "pacman -S --needed --noconfirm mingw-w64-i686-xz"
 
 # replace xz -T0 by xz -T1, workaround wine-staging bug 241 - https://bugs.wine-staging.com/show_bug.cgi?id=241
 echo replace xz -T0 by xz -T1, workaround wine-staging bug 241
@@ -62,6 +62,6 @@ sed -i 's/xz -d -c/\/mingw32\/bin\/xz -d -c/' ${MSYS_ROOT}/usr/bin/autopoint
 sed -i "s/flock_implemented = 'yes'/flock_implemented = 'no'/" ${MSYS_ROOT}/usr/bin/autom4te
 
 # replace mingw msgmerge and msgfmt by msys2 msgmerge and msgfmt, workaround wine staging bug 485 - https://bugs.wine-staging.com/show_bug.cgi?id=485
-msys2-wrapper "pacman -S --needed --noconfirm mingw-w64-i686-gettext"
-msys2-wrapper "cp /usr/bin/msgmerge.exe /mingw32/bin/msgmerge.exe"
-msys2-wrapper "cp /usr/bin/msgfmt.exe /mingw32/bin/msgfmt.exe"
+msys2-shell -c "pacman -S --needed --noconfirm mingw-w64-i686-gettext"
+msys2-shell -c "cp /usr/bin/msgmerge.exe /mingw32/bin/msgmerge.exe"
+msys2-shell -c "cp /usr/bin/msgfmt.exe /mingw32/bin/msgfmt.exe"
